### PR TITLE
Alternative matching & ordering

### PR DESCRIPTION
**Pull request by nevesnunes**
Adds a fuzzy matching algorithm and the option to sort results by relevancy, calculated according to match length and position.

### CODE REVIEW

**Comment by daniellandau** [comment]
Sorry, I haven't have much time to look into this. I'll try running the new algorithms for a couple of days and then take a closer look at the code.

**Comment by daniellandau** [comment]
It's taken a while, but now I've gotten a good look.

I made some changes in https://github.com/daniellandau/switcher/commit/7e7ed6f3100fafc948aeb83699126bbacda786ac, can you take a look?

**Comment by nevesnunes** [comment]
No worries. The changes look fine to me, I've merged them and also pushed a fix regarding that workspace bug.

**Comment by daniellandau** [comment]
Thanks, this is awesome!

**Pull request merged**
