### PR TITLE
Control panel and other stuff

### PR DESCRIPTION
**Pull request by daniellandau**
@goodwillcoding do you want to take another look at this? This code seems to work fine for me on X11, but on Wayland the settings panels don't come up at all.

### CODE REVIEW

**Comment by PHLAK** [comment]
Thanks for the change to enable <kbd>Ctrl</kbd>+<kbd>Enter</kbd> to launch a new instance. I pulled down this code and tested it and it seems to work. However, if I open the swither and select an app that's NOT already running and press <kbd>Ctrl</kbd>+<kbd>Enter</kbd> the launcher stays on screen. I'd expect it to disappear.

**Comment by daniellandau** [comment]
That's been a feature for a long time already to allow opening multiple apps quickly.

**Comment by PHLAK** [comment]
Maybe that should use a different key combination now so it doesn't conflict with the new behavior of <kbd>Ctrl</kbd>+<kbd>Enter</kbd>. Maybe switch it to <kbd>Alt</kbd>+<kbd>Enter</kbd> or <kbd>Shift</kbd>+<kbd>Enter</kbd>?

**Comment by daniellandau** [comment]
Please check the new commit. This behavior (ctrl+enter on either windows or apps opens a new window and keeps the switcher active) matches quite closely what the overview does. I think we are closing in on a good design, which wouldn't be the case without your input!

**Comment by daniellandau** [comment]
Now this works for me in both X11 and Wayland sessions. I'll read through the code with fresh eyes after some time still and any testing is also appreciated.

Fixes https://github.com/daniellandau/switcher/issues/84

**Pull request merged**
