### PR TITLE
Gnome shell 47 compatibility

### LINKED ISSUE #170: extension does not work with gnome 47.0
Plugin does not work with gnome 47.0

### PR DESCRIPTION
**Pull request by Nevon**
Tested it out briefly in gnome 47 and seems to work just fine. Fixes #170

### CODE REVIEW

**Comment by benjamin-rood** [comment]
Works for me on `6.10.10-arch1-1` + `GNOME 47.0` :+1: 
Thank you!

**Comment by PHLAK** [comment]
These changes got an existing Switcher installation working again for me, however, I also tried installing Switcher (with these changes) on a fresh OS installation and it's not working. Specifically, when attempting to access the extension settings I get the following error with a stack trace. 

```
Error: Argument to the constructor of Popover should be a plain JS object with properties to set
```

Also, upon further inspections none of the dconf settings are created (probably due to the errors above).

Unfortunately, it seems like additional work is needed to get this updated for GNOME 47.

**Comment by GrantByrn3** [comment]
Can confirm that this is working for me as well. Tested this out on Fedora Workstation 41.

**Comment by GrantByrne** [comment]
Actually, I spoke too soon. Tried this on another machine and it's not working when I press the keyboard shortcut and I get the following error when I open up the settings.

```
Error: Argument to the constructor of Popover should be a plain JS object with properties to set

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:39:56
  buildOnboarding@file:///home/grant/.local/share/gnome-shell/extensions/switcher@landau.fi/prefs.js:363:19
  buildWidgets@file:///home/grant/.local/share/gnome-shell/extensions/switcher@landau.fi/prefs.js:97:44
  buildPrefsWidget@file:///home/grant/.local/share/gnome-shell/extensions/switcher@landau.fi/prefs.js:23:3
  fillPreferencesWindow@file:///home/grant/.local/share/gnome-shell/extensions/switcher@landau.fi/prefs.js:411:22
  _loadPrefs@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:39:24
  async*_init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:24:14
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:15:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:138:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:373:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:408:34
  _init/GLib.MainLoop.prototype.runAsync/</<@resource:///org/gnome/gjs/modules/core/overrides/GLib.js:263:34

```

**Comment by daniellandau** [comment]
Shell 47 compatibility now in via #172, so closing this. Thank you for providing a stop gap solution so people who are comfortable installing manually could use it while I was busy with life!

**Pull request closed without merging**
