### PR TITLE
Option to show switcher on active display instead of primary

### PR DESCRIPTION
**Pull request by markonius**
This should solve #92 , #43 and partially #80

### CODE REVIEW

**Comment by daniellandau** [comment]
Thanks! I'll test this out ASAP.

**Comment by trst** [comment]
Hey! I’ll test and give feedback as well 🥳

**Comment by markonius** [comment]
Hmm, I usually work with gitlab, can I somehow resolve your change request or what's the procedure. Also, I ammended my commit, so "View changes" goes nowhere. Should I have not done that?

**Comment by daniellandau** [comment]
This is fine, thanks!

**Pull request merged**
