### PR TITLE
bug #10: associate apps with F keys for even faster switching

### PR DESCRIPTION
**Pull request by emmanueltouzery**
ok I worked on a patch for the bug #10 which I opened.
this is very lightly tested but it seems to work fine. I keep the hash between key and app in memory for the whole runtime because otherwise I would get different orders every time. That's to help the user by making sure that eg F4 is that specific firefox window and it's going to stay like that until logout.

however that conflicts a bit with the order displayed in the GUI. after a while you have a gui displayin the keyboard shortcuts as for instance F4, F6, F1, and so on... Messy.

Maybe we could add an option "keep the order consistent", to go with this way of using the app?

### CODE REVIEW

**Comment by emmanueltouzery** [comment]
also the F keys are not really great, quite far on the keyboard, but as I said in the bug, presumably we want the user to be able to filter using digits too. Otherwise we could map to key shortcuts. Not sure.

**Comment by daniellandau** [comment]
First of all thanks for providing improvements!

So as you have noticed, the order is not based on when each window has been first opened, but on when each window has last been in focus, meaning that it is not at all stable. Even if there was an option not to sort by activation, the user could still close windows, leading to a shift in all the windows below.

Having stable keyboard shortcuts to windows is something that I think at least some other window managers provide by default and wouldn't be too hard to make as an extension in Gnome either, but I don't think it meshes well with this particular extension.

Instead, do you think you'd find useful an option to immediately activate the n'th window by pressing F[n], or optionally just the number? I personally use the function keys for other things already, but never end up using plain numbers to filter, so I might even use the "activate by number" option, if such a thing were to exist. Opinions?

**Comment by emmanueltouzery** [comment]
Yes, good points. Very reasonable. The truth is that I discovered your extension only today ;-) so I'm not completely sure what it is I want, really. I guess let's do what you suggest, then I'll have to try and see whether it works for me, or maybe I take your extension and modify it for my taste and release it separately, or maybe I just go all the way and switch to i3 :-)

So, regarding the F[n] and optionally normal numbers... We would add a new option in the settings?

Allow quickselect:
( ) through the F[n] keys
( ) through the digit keys

Something like that? Or we just go with the digits and no option? Another option is win-w win-<digit> but then win-6 for instance is a bit annoying, the keys are a bit far away. If we do with options, which one would you like by default?

For me I think I'll try with the digit keys. I assume it's possible to steal them from the text entry btw, we might hit a problem there but hopefully not.

**Comment by daniellandau** [comment]
I'd like to keep the basic settings as simple as possible and with the least number of undiscoverable and surprising behaviors, so by default neither function or digit keys should activate. I'd make it optional to use one or both methods.

Do you want to work on the code?

**Comment by emmanueltouzery** [comment]
I can work on it, but if you are ok to do it, I'd rather if you do it ;-)
I guess it's low-priority for you and I'd like to have it soon so I guess it's better I work on it.

**Comment by daniellandau** [comment]
I'm at $DAYJOB now, so won't have time to code in several hours :)

If you can do something that works, I'll be happy to wrangle it to my liking and taste in code style.

**Comment by emmanueltouzery** [comment]
ok i've been working on this, I'm in a good shape. I'll update the PR through the week-end. I just have one issue: I added the new option in schemas/org.gnome.shell.extensions.switcher.gschema.xml, and I can't read it from the main window or from preferences. I get:

    (gnome-shell:10357): GLib-GIO-ERROR **: Settings schema 'org.gnome.shell.extensions.switcher' does not contain a key named 'activate-by-key'

and it's a bit inconvenient because it crashes the whole shell ;-)
I'm pretty sure you know by heart how to I register that option so that this works?

I also have yet to try activation by digits because of the risk of the text field eating it, but I'll see how it goes when I get there.

**Comment by emmanueltouzery** [comment]
This is what I added to the gschema.xml btw:

    +        <key type="u" name="activate-by-key">
    +            <default>0</default>
    +            <summary>Activate by pressing the index in the list: 0=No, 1=Function keys, 2=Digit keys</summary>
    +        </key>

**Comment by daniellandau** [comment]
> I'm pretty sure you know by heart how to I register that option so that this works?

Sadly yes, I wish there was better documentation overall, or I should probably add a Makefile for this (and making a zip package for upload).

You have to run

    glib-compile-schemas schemas

in the top directory of the extension.

**Comment by emmanueltouzery** [comment]
ok, I've updated the PR as discussed. Two things maybe:

* i have to force a width for the last column displaying the key to press to activate the window, otherwise each row has a different width depending on the length of the text (eg F12 is longer than F1). But I had trouble in calculating the ideal width. I couldn't find any API to measure text width so I just say, max width divided by 15... It's pretty frail. Hopefully you find a better way...
* i was thinking that for the digits if we have >10 windows we could then continue with the F keys, eg 1, 2, 3, 9, 0, F1, F2, ... But it may be overengineered and messy. Your call

appart from that I think it's OK.

**Comment by daniellandau** [comment]
Seems to work, great! I have a couple of small issues with your code, but I'll fix them myself tomorrow before merging.

**Comment by emmanueltouzery** [comment]
Btw when doing the cleanups I think you can remove the `index` parameter that I added to `makeBox`, I believe it's not used anymore.

**Comment by daniellandau** [comment]
Merged, thank you very much!

You can check commits e57248176b..a9042cf239 if you want to know what I changed.

**Comment by emmanueltouzery** [comment]
hmm your commit https://github.com/daniellandau/switcher/commit/a9042cf23941a5c95a21f84ae3ca7b6a925d0f58 broke the "numbers" mode. `entry.set_input_purpose(Gtk.InputPurpose.ALPHA);` is needed to let us catch digits.  Otherwise thanks for the tip about `wmctrl`, I didn't know about it and will be sure to check it out!

**Comment by daniellandau** [comment]
Does it really for you? What version of Gnome Shell are you running?

https://people.gnome.org/~gcampagna/docs/Gtk-3.0/Gtk.InputPurpose.html seems to say that the input purpose is useful for on screen keyboards to know what keyboard to show, but it doesn't guarantee any strict rules. For me removing it didn't have any effect.

**Comment by emmanueltouzery** [comment]
Running gnome 3.18, fedora 23. Admittedly it's a bit of a hack, but I expected trouble fighting with the text entry for the number keys.

**Comment by emmanueltouzery** [comment]
Surprised you don't see the problems. You type '5' and it doesn't go in the entry? Maybe you tested only function keys?

**Comment by daniellandau** [comment]
It goes to the entry with or without the input purpose. On key release the correct window is still activated.

**Comment by emmanueltouzery** [comment]
huh ok it worked now. i've seen it fail, as in the extension didn't catch the key, always up to now, including with your code just before. Why it was failing and now it works is confusing me, but well... forget about it for now. It works also for me now, so let's call it a day, if I see the problem again I'll open a bug.

**Comment by daniellandau** [comment]
Ok, great! Thanks again!

**Pull request merged**
