### PR TITLE
Async and combined switcher

### PR DESCRIPTION
**Pull request by daniellandau**
Supersedes https://github.com/daniellandau/switcher/pull/121

Fixes:
* https://github.com/daniellandau/switcher/issues/115
* https://github.com/daniellandau/switcher/issues/109
* https://github.com/daniellandau/switcher/issues/123
* https://github.com/daniellandau/switcher/issues/122
* https://github.com/daniellandau/switcher/issues/119

This is quite a lot of new code. Everything seems to be working on my machine now, but I'd appreciate if someone can test this version. Otherwise I'll let it marinate for some days and try to do a self-review with fresh eyes later.

### CODE REVIEW

**Comment by PHLAK** [comment]
Just tested the latest code from `master` (including these changes) and noticed that <kbd>Ctrl</kbd>+ <kbd>Space</kbd> no longer switches between the switcher and launcher.

**Comment by daniellandau** [comment]
There is no separate switcher and launcher anymore.

**Comment by PHLAK** [comment]
@daniellandau How can I launch a new instance of an app when one is already running then?

**Comment by daniellandau** [comment]
I was filtering already open apps out, but they could instead be just sorted down. Hopefully this commit in the other PR solves it for you https://github.com/daniellandau/switcher/pull/127/commits/790a94f104385e196ac3df79df62b8ae430a1361

**Comment by PHLAK** [comment]
Thanks @daniellandau, that commit does show both now. However, I find this is a little bit confusing (especially when the window title is the same name as the application) and would like to propose an alternate idea.

In Gnome when an app is already running clicking on the icon in the panel while holding <kbd>Ctrl</kbd> will force open a new window/instance. Would it be possible to implement the same behavior with the switcher? So instead of showing duplicate entries for an application you could force open an new window/instance with <kbd>Ctrl</kbd>+<kbd>Enter</kbd>?

I can create a new issue for this if you'd like.

**Comment by daniellandau** [comment]
No need for a new issue. I'm not at my computer now, but I'll try to get that code written ASAP

**Comment by PHLAK** [comment]
Awesome, thanks!

**Comment by daniellandau** [comment]
Today I Learned about that ctrl click behaviour in the overview. Thanks for the design input, there's now new code in the other PR

**Pull request merged**
