### PR TITLE
Puts the shorcut box in the far left.

### PR DESCRIPTION
**Pull request by wilcus**
This makes easy to see which number have to be typed (specially in big width screen)

### CODE REVIEW

**Comment by daniellandau** [comment]
Somewhere in the left does make it faster to figure out the correct key, but I think the leftmost should be the icon. How about right after the icon.

**Comment by wilmoz** [comment]
right after icon make me happy too.

**Comment by wilmoz** [comment]
@daniellandau I've updated my patch

**Comment by daniellandau** [comment]
Sorry for taking a while. Thanks for the improvement!

**Pull request merged**
